Update readme

diff --git a/.github/workflows/auto-build-publish-test.yml b/.github/workflows/auto-build-publish-test.yml
--- a/.github/workflows/auto-build-publish-test.yml
+++ b/.github/workflows/auto-build-publish-test.yml
@@ -62,10 +62,10 @@ jobs:
       - name: Post Step to Test the Auto Build-Publish post step
         uses: gacts/run-and-post-run@v1
         with:
-          post: >-
-            count=$(jf rt search "artifactory-build-info/${GITHUB_WORKFLOW}/${GITHUB_RUN_NUMBER}-*" --count 2>/dev/null)
-            exit_code=$?
-            if [ $exit_code -ne 0 ] || [ "$count" -eq 0 ]; then
-              echo "Search command failed or no build info found."
-              exit 1
+          post: |
+            count=$(jf rt search "artifactory-build-info/${GITHUB_WORKFLOW}/${GITHUB_RUN_NUMBER}-*" --count 2>/dev/null); \
+            exit_code=$?; \
+            if [ $exit_code -ne 0 ] || [ "$count" -eq 0 ]; then \
+              echo "Search command failed or no build info found."; \
+              exit 1; \
             fi
