Update readme

diff --git a/.github/workflows/auto-build-publish-test.yml b/.github/workflows/auto-build-publish-test.yml
--- a/.github/workflows/auto-build-publish-test.yml
+++ b/.github/workflows/auto-build-publish-test.yml
@@ -40,11 +40,12 @@ jobs:
             cat stderr.log /
             exit_code=$? /
             if [ $exit_code -ne 0 ]; then /
-              exit 1 /
+              echo "Command failed with exist error 1."; /
+              exit 1; /
             fi /
             if [ "$count" -eq 0 ]; then /
-              echo "No build info found." /
-              exit 1 /
+              echo "No build info found."; /
+              exit 1; /
             fi
 
       - name: Setup JFrog CLI
