Update readme

diff --git a/.github/workflows/auto-build-publish-test.yml b/.github/workflows/auto-build-publish-test.yml
--- a/.github/workflows/auto-build-publish-test.yml
+++ b/.github/workflows/auto-build-publish-test.yml
@@ -63,11 +63,8 @@ jobs:
         uses: gacts/run-and-post-run@v1
         with:
           post: |
-            # Search for the build info and get the count
             count=$(jf rt search "artifactory-build-info/${GITHUB_WORKFLOW}/${GITHUB_RUN_NUMBER}-*" --count 2>/dev/null)
+            exit_code=$?
             
-            # Exit with an error if the search command failed or result is zero
-            if [ $exit_code -ne 0 ] || [ "count" -eq 0 ]; then
-             echo "Search command failed or no build info found."
-             exit 1
-            fi
+            if [ $exit_code -ne 0 ] || [ "$count" -eq 0 ]; then
+              echo "Search command failed or no build info found."
